version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      # bootJar task outputs to build/libs/<name>.jar
      - ./gradlew bootJar
  post_build:
    commands:
      # move the jar (by wildcard, agnostic to its name) to top level app.jar
      - mv build/libs/*.jar application.jar
artifacts:
  files:
    # publish the now top level app.jar as the artifact
    - application.jar